### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by hugurp** [internet4000/i4k-image-feed#1]
Image quality is now low res, since the images are supposed to be a grid in the first use case.

Should we:
- make images better quality? comes with the downside of having larger images to download
- make it possible to seleect which image quality to display, in the root html element attribute?
- implement responsive images

**Comment by oskarrough** [comment]
For reference we have these three sizes available through the API:

- 150px (thumbnail)
- 320px (low)
- 640px (standard)

Since we do not know the dimensions of the image-feed, I vote either an option to choose between one of the three sizes or responsive images. To properly do that we'd need to include lazysizes to the bundle and use its `data-sizes="auto"`?

**Comment by hugurp** [comment]
Increased to maximum here https://github.com/internet4000/i4k-image-feed/commit/0b350ec69214c359c6b37cfe3aefdb9bbf90465a
